# Generated by Django 4.1.5 on 2023-07-10 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepageapp', '0001_initial'),
        ('firebase_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cust_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_user_first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('cust_user_last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('cust_user_middle_name', models.CharField(max_length=50, null=True, verbose_name='middle name')),
                ('cust_user_preferred_name', models.CharField(help_text='The preffered name.', max_length=50, null=True, verbose_name='preferred name')),
                ('cust_user_phone_number', models.CharField(help_text='enter a valid US phone number.', max_length=20, null=True)),
                ('cust_user_country_code', models.CharField(default='+1', max_length=10)),
                ('cust_user_email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=128)),
                ('cust_user_start_date', models.DateTimeField(null=True)),
                ('cust_user_discharge_date', models.DateTimeField(blank=True, null=True)),
                ('cust_user_avator_path', models.CharField(max_length=500)),
                ('cust_user_address_01', models.CharField(max_length=50)),
                ('cust_user_address_02', models.CharField(max_length=50)),
                ('cust_user_address_city', models.CharField(max_length=50)),
                ('cust_user_address_state', models.CharField(max_length=2)),
                ('cust_user_address_zip', models.CharField(max_length=50)),
                ('cust_user_is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('cust_user_linkage_is_confirmed', models.BooleanField(default=False)),
                ('cust_user_last_linked_date', models.DateTimeField(null=True)),
                ('customer_user_lastest_ip_address', models.GenericIPAddressField(null=True)),
                ('cust_user_created_at', models.DateTimeField(auto_now_add=True)),
                ('cust_user_last_updated_at', models.DateTimeField(auto_now=True)),
                ('cust_user_linked_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_customers', to='homepageapp.customersnewsql02model')),
                ('cust_user_linked_firebaseuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firebase_auth_app.firebaseuser')),
            ],
            options={
                'verbose_name': 'customeruser',
                'verbose_name_plural': 'customerusers',
                'db_table': 'customerusers_new_03',
            },
        ),
    ]
