# Generated by Django 4.1.5 on 2023-05-29 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0079_alter_paymentsmodel_payment_account_class_and_more'),
        ('customer_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='cust_user_linked_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_customers', to='homepageapp.customersnewsql02model'),
        ),
    ]
