# Generated by Django 4.1.5 on 2023-05-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_users', '0002_alter_customeruser_cust_user_linked_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='cust_user_linkage_is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
