# Generated by Django 4.1.5 on 2023-06-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_users', '0003_alter_customeruser_cust_user_linkage_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='cust_user_middle_name',
            field=models.CharField(max_length=50, null=True, verbose_name='middle name'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='cust_user_preferred_name',
            field=models.CharField(help_text='The preffered name.', max_length=50, null=True, verbose_name='preferred name'),
        ),
    ]
