# Generated by Django 4.1.5 on 2023-06-09 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firebase_auth_app', '0001_initial'),
        ('customer_users', '0004_customeruser_cust_user_middle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='cust_user_linked_firebaseuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firebase_auth_app.firebaseuser'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='customer_user_lastest_ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
