# Generated by Django 4.1.5 on 2023-06-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_users', '0005_customeruser_cust_user_linked_firebaseuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='cust_user_phone_number',
            field=models.CharField(help_text='enter a valid US phone number.', max_length=20),
        ),
    ]
