# Generated by Django 4.1.5 on 2023-06-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_users', '0006_alter_customeruser_cust_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='cust_user_phone_number',
            field=models.CharField(help_text='enter a valid US phone number.', max_length=20, null=True),
        ),
    ]
