# Generated by Django 4.1.5 on 2023-04-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclesnewsql02model',
            old_name='vechicle_used_level',
            new_name='vehicle_used_level',
        ),
    ]
