# Generated by Django 4.1.5 on 2023-04-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0005_makesnewsql02model_modelsnewsql02model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressesnewsql02model',
            name='address_zip_code',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
