# Generated by Django 4.1.5 on 2023-04-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0006_alter_addressesnewsql02model_address_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressesnewsql02model',
            name='address_line_01',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
