# Generated by Django 4.1.5 on 2023-04-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0007_alter_addressesnewsql02model_address_line_01'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressesnewsql02model',
            name='address_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='addressesnewsql02model',
            name='address_company_or_ATTN',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='addressesnewsql02model',
            name='address_line_01',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='addressesnewsql02model',
            name='address_state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
