# Generated by Django 4.1.5 on 2023-04-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0008_alter_addressesnewsql02model_address_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclesnewsql02model',
            name='vehicle_customer_new_uid',
        ),
    ]
