# Generated by Django 4.1.5 on 2023-04-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0009_remove_vehiclesnewsql02model_vehicle_customer_new_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cannedjobsnewsql02model',
            name='canned_job_last_updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cannedjobsnewsql02model',
            name='canned_job_vehicle_class',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
