# Generated by Django 4.1.5 on 2023-04-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0010_cannedjobsnewsql02model_canned_job_last_updated_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineitemsnewsql02model',
            old_name='Line_item_cost',
            new_name='line_item_cost',
        ),
        migrations.RenameField(
            model_name='lineitemsnewsql02model',
            old_name='line_Item_parent_line_item_id',
            new_name='line_item_parent_line_item_id',
        ),
    ]
