# Generated by Django 4.1.5 on 2023-04-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0011_rename_line_item_cost_lineitemsnewsql02model_line_item_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitemsnewsql02model',
            name='line_item_account_class_id',
            field=models.IntegerField(null=True),
        ),
    ]
