# Generated by Django 4.1.5 on 2023-04-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0014_alter_lineitemsnewsql02model_line_item_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitemtaxesnewsql02model',
            name='line_item_tax_id',
            field=models.IntegerField(null=True),
        ),
    ]
