# Generated by Django 4.1.5 on 2023-04-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0015_alter_lineitemtaxesnewsql02model_line_item_tax_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitemsnewsql02model',
            name='line_item_order_revision_id',
            field=models.IntegerField(null=True),
        ),
    ]
