# Generated by Django 4.1.5 on 2023-04-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0016_alter_lineitemsnewsql02model_line_item_order_revision_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitemsnewsql02model',
            name='line_item_labor_only_sale',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='lineitemsnewsql02model',
            name='line_item_labor_sale',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='lineitemsnewsql02model',
            name='line_item_package_sale',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='lineitemsnewsql02model',
            name='line_item_part_only_sale',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='lineitemsnewsql02model',
            name='line_item_part_sale',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='lineitemsnewsql02model',
            name='line_item_sublet_sale',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='lineitemsnewsql02model',
            name='line_item_tire_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
