# Generated by Django 4.1.5 on 2023-04-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0017_alter_lineitemsnewsql02model_line_item_labor_only_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitemsnewsql02model',
            name='line_item_cost',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='lineitemsnewsql02model',
            name='line_item_sale',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
