# Generated by Django 4.1.5 on 2023-04-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0018_alter_lineitemsnewsql02model_line_item_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitemsnewsql02model',
            name='line_item_description',
            field=models.CharField(max_length=2000),
        ),
    ]
