# Generated by Django 4.1.5 on 2023-04-09 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0019_alter_lineitemsnewsql02model_line_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxesModel',
            fields=[
                ('tax_id', models.AutoField(primary_key=True, serialize=False)),
                ('tax_description', models.CharField(max_length=30, null=True)),
                ('tax_applied_gl_code', models.IntegerField()),
                ('tax_item_created_at', models.DateTimeField(auto_now_add=True)),
                ('tax_last_updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'tax',
                'verbose_name_plural': 'taxes',
                'db_table': 'taxes_new_03',
                'ordering': ['-tax_id'],
            },
        ),
        migrations.AlterField(
            model_name='lineitemtaxesnewsql02model',
            name='line_item_tax_charged',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='lineitemtaxesnewsql02model',
            name='line_item_tax_rate',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.CreateModel(
            name='CustomerTaxesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customertaxes_last_updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepageapp.customersnewsql02model')),
                ('tax_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepageapp.taxesmodel')),
            ],
            options={
                'verbose_name': 'customertax',
                'verbose_name_plural': 'customertaxes',
                'db_table': 'customertaxes_new_03',
                'ordering': ['-tax_id', '-customer_id'],
            },
        ),
    ]
