# Generated by Django 4.1.5 on 2023-04-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0020_taxesmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersnewsql02model',
            name='emails',
            field=models.ManyToManyField(related_name='taxes', through='homepageapp.CustomerEmailsNewSQL02Model', to='homepageapp.emailsnewsql02model'),
        ),
    ]
