# Generated by Django 4.1.5 on 2023-04-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0021_customersnewsql02model_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersnewsql02model',
            name='phones',
            field=models.ManyToManyField(related_name='phones', through='homepageapp.CustomerPhonesNewSQL02Model', to='homepageapp.phonesnewsql02model'),
        ),
        migrations.AddField(
            model_name='customersnewsql02model',
            name='taxes',
            field=models.ManyToManyField(related_name='taxes', through='homepageapp.CustomerTaxesModel', to='homepageapp.taxesmodel'),
        ),
        migrations.AlterField(
            model_name='customersnewsql02model',
            name='emails',
            field=models.ManyToManyField(related_name='emails', through='homepageapp.CustomerEmailsNewSQL02Model', to='homepageapp.emailsnewsql02model'),
        ),
    ]
