# Generated by Django 4.1.5 on 2023-04-09 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0022_customersnewsql02model_phones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountClassModel',
            fields=[
                ('account_class_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(max_length=30, null=True)),
                ('account_last_updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'accountclass',
                'verbose_name_plural': 'accountclasses',
                'db_table': 'accountclasses_new_03',
                'ordering': ['-account_class_id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransactionsModel',
            fields=[
                ('payment_transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_last_updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'paymenttransactions_new_03',
                'ordering': ['-payment_transaction_id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentsModel',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_record_number', models.IntegerField(null=True)),
                ('payment_date', models.DateTimeField(null=True)),
                ('payment_check_data', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_auth_data', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_invoice_status_id', models.IntegerField(null=True)),
                ('payment_is_NSF', models.BooleanField(default=False)),
                ('payment_is_NSF_reversal', models.BooleanField(default=False)),
                ('payment_is_fee_payment', models.BooleanField(default=False)),
                ('payment_total_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_deletion_date', models.DateTimeField(null=True)),
                ('payment_verification_data', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_receipt_one', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_receipt_two', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_receipt_three', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_last_updated_date', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_account_class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepageapp.accountclassmodel')),
                ('payment_customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepageapp.customersnewsql02model')),
                ('payment_repair_order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepageapp.repairordersnewsql02model')),
                ('payment_transcation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepageapp.paymenttransactionsmodel')),
            ],
            options={
                'db_table': 'payments_new_03',
                'ordering': ['-payment_id'],
            },
        ),
    ]
