# Generated by Django 4.1.5 on 2023-04-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0023_accountclassmodel_paymenttransactionsmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequestModel',
            fields=[
                ('service_appointment_request_uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('service_appointment_requested_datetime', models.DateTimeField(blank=True)),
                ('service_appointment_type', models.IntegerField()),
                ('service_appointment_first_name', models.CharField(blank=True, max_length=60, null=True)),
                ('service_appointment_last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('service_appointment_middle_name', models.CharField(blank=True, max_length=60, null=True)),
                ('service_appointment_contact_phone_main', models.CharField(blank=True, max_length=60, null=True)),
                ('service_appointment_contact_email_address', models.EmailField(blank=True, max_length=254)),
                ('service_appointment_preferred_contact_method', models.CharField(blank=True, max_length=100)),
                ('service_appointment_shop_comments', models.TextField(blank=True)),
                ('service_appointment_customer_id', models.IntegerField(blank=True)),
                ('service_appointment_vehicle_id', models.IntegerField(blank=True)),
                ('service_appointment_customer_details', models.CharField(blank=True, max_length=2000, null=True)),
                ('service_appointment_vehicle_details', models.CharField(blank=True, max_length=2000, null=True)),
                ('service_appointment_fleet_details', models.CharField(blank=True, max_length=2000, null=True)),
                ('service_appointment_waiting_options', models.CharField(blank=True, max_length=100)),
                ('service_appointment_sub_categories', models.CharField(blank=True, max_length=300)),
                ('service_appointment_status', models.IntegerField()),
                ('service_appointment_customer_comments', models.TextField()),
                ('service_appointment_final_estimated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('service_appointment_confirmed_UTC_datetime', models.DateTimeField(blank=True)),
                ('service_appointment_submitted_UTC_datetime', models.DateTimeField(blank=True)),
                ('service_appointment_confirmed_by_employee_id', models.IntegerField(blank=True)),
                ('service_appointment_repair_order_id', models.IntegerField(blank=True)),
                ('service_appointment_is_converted_to_repair_order', models.BooleanField(default=False)),
                ('service_appointment_is_inactive', models.BooleanField(default=False, null=True)),
                ('service_appointment_created_at', models.DateTimeField(auto_now_add=True)),
                ('service_appointment_last_udpated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'appointmentrequests_new_03',
                'ordering': ['-service_appointment_request_uid'],
            },
        ),
    ]
