# Generated by Django 4.1.5 on 2023-04-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0024_appointmentrequestmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_description', models.CharField(blank=True, max_length=200)),
                ('category_display', models.IntegerField(blank=True, null=True)),
                ('category_created_at', models.DateTimeField(auto_now_add=True)),
                ('category_last_updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'categories_new_03',
                'ordering': ['-category_id'],
            },
        ),
        migrations.RenameField(
            model_name='customertaxesmodel',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='noteitemsnewsql02model',
            old_name='line_item_id',
            new_name='line_item',
        ),
    ]
