# Generated by Django 4.1.5 on 2023-04-11 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0028_alter_repairordersnewsql02model_repair_order_billed_hours_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentRequestModel',
        ),
    ]
