# Generated by Django 4.1.5 on 2023-04-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0029_delete_appointmentrequestmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneDescModel',
            fields=[
                ('phone_desc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_desc', models.CharField(max_length=50, null=True)),
                ('phone_order', models.IntegerField()),
                ('phone_desc_default_type', models.CharField(max_length=5, null=True)),
                ('phone_desc_created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_desc_last_updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'phonedesc',
                'verbose_name_plural': 'phonedescs',
                'db_table': 'phonedescs_new_03',
                'ordering': ['-phone_desc_id'],
            },
        ),
    ]
