# Generated by Django 4.1.5 on 2023-04-12 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0030_phonedescmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonesnewsql02model',
            name='phone_desc_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepageapp.phonedescmodel'),
        ),
    ]
