# Generated by Django 4.1.5 on 2023-04-12 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0031_alter_phonesnewsql02model_phone_desc_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonesnewsql02model',
            old_name='phone_desc_id',
            new_name='phone_desc',
        ),
    ]
