# Generated by Django 4.1.5 on 2023-04-13 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0032_rename_phone_desc_id_phonesnewsql02model_phone_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitemtaxesnewsql02model',
            name='line_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='homepageapp.lineitemsnewsql02model'),
        ),
        migrations.AlterField(
            model_name='noteitemsnewsql02model',
            name='line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noteitems', to='homepageapp.lineitemsnewsql02model'),
        ),
    ]
