# Generated by Django 4.1.5 on 2023-04-13 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0034_alter_lineitemsnewsql02model_line_item_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineitemsnewsql02model',
            old_name='line_item_category_id',
            new_name='line_item_category',
        ),
    ]
