# Generated by Django 4.1.5 on 2023-04-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0036_partsmodel_partitemmodel_laboritemmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsmodel',
            name='part_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
