# Generated by Django 4.1.5 on 2023-04-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0037_alter_partsmodel_part_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsmodel',
            name='part_account_class_id',
            field=models.IntegerField(null=True),
        ),
    ]
