# Generated by Django 4.1.5 on 2023-04-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0038_alter_partsmodel_part_account_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitemmodel',
            name='part_discount_description_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='partitemmodel',
            name='part_item_manufacture_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='partitemmodel',
            name='part_item_part_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='partitemmodel',
            name='part_item_vendor_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partitemmodel',
            name='part_item_vendor_id',
            field=models.IntegerField(null=True),
        ),
    ]
