# Generated by Django 4.1.5 on 2023-04-14 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0039_alter_partitemmodel_part_discount_description_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitemmodel',
            name='line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_lineitems', to='homepageapp.lineitemsnewsql02model'),
        ),
    ]
