# Generated by Django 4.1.5 on 2023-04-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0040_alter_partitemmodel_line_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitemmodel',
            name='part_item_part_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
