# Generated by Django 4.1.5 on 2023-04-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0041_alter_partitemmodel_part_item_part_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitemmodel',
            name='part_item_part_no',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='partitemmodel',
            name='part_item_vendor_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
