# Generated by Django 4.1.5 on 2023-04-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0042_alter_partitemmodel_part_item_part_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partitemmodel',
            name='part_item_is_Committed',
        ),
        migrations.AlterField(
            model_name='partitemmodel',
            name='part_item_commission_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='partitemmodel',
            name='part_item_is_committed',
            field=models.BooleanField(default=False),
        ),
    ]
