# Generated by Django 4.1.5 on 2023-04-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0043_remove_partitemmodel_part_item_is_committed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitemmodel',
            name='part_item_confirmed_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='partitemmodel',
            name='part_item_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='partitemmodel',
            name='part_item_unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='partitemmodel',
            name='part_item_unit_list',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='partitemmodel',
            name='part_item_unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='partitemmodel',
            name='part_item_unit_sale',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
