# Generated by Django 4.1.5 on 2023-04-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0044_alter_partitemmodel_part_item_confirmed_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitemmodel',
            name='part_item_part_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
