# Generated by Django 4.1.5 on 2023-04-14 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0045_alter_partitemmodel_part_item_part_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboritemmodel',
            name='line_item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_lineitems', to='homepageapp.lineitemsnewsql02model'),
        ),
    ]
