# Generated by Django 4.1.5 on 2023-04-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0046_alter_laboritemmodel_line_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboritemmodel',
            old_name='line_item_id',
            new_name='line_item',
        ),
    ]
