# Generated by Django 4.1.5 on 2023-04-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0047_rename_line_item_id_laboritemmodel_line_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrakesModel',
            fields=[
                ('brake_id', models.AutoField(primary_key=True, serialize=False)),
                ('brake_system_type', models.CharField(max_length=150, null=True)),
                ('brake_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'brake',
                'verbose_name_plural': 'brakes',
                'db_table': 'brakes_new_03',
                'ordering': ['-brake_id'],
            },
        ),
        migrations.CreateModel(
            name='EnginesModel',
            fields=[
                ('engine_id', models.AutoField(primary_key=True, serialize=False)),
                ('engine_displacement_CID', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('engine_displacement_Liter', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('engine_number_of_cylinder', models.IntegerField(null=True)),
                ('engine_valve_per_cyclinder', models.IntegerField(null=True)),
                ('engine_head_configuration_type', models.CharField(blank=True, max_length=100, null=True)),
                ('engine_boost_type', models.CharField(blank=True, max_length=100, null=True)),
                ('engine_ignition_system', models.CharField(blank=True, max_length=100, null=True)),
                ('engine_vin_code', models.CharField(blank=True, max_length=5, null=True)),
                ('engine_fuel_system', models.CharField(blank=True, max_length=100, null=True)),
                ('engine_fuel_delivery_method_type', models.CharField(blank=True, max_length=100, null=True)),
                ('engine_fuel_type', models.CharField(blank=True, max_length=100, null=True)),
                ('engine_fuel_control_type', models.CharField(blank=True, max_length=100, null=True)),
                ('engine_block_configuration', models.CharField(blank=True, max_length=100, null=True)),
                ('engine_fuel_system_configuration', models.CharField(blank=True, max_length=100, null=True)),
                ('engine_created_at', models.DateTimeField(auto_now_add=True)),
                ('engine_last_updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'engine',
                'verbose_name_plural': 'engines',
                'db_table': 'engines_new_03',
                'ordering': ['-engine_id'],
            },
        ),
        migrations.CreateModel(
            name='GVWsModel',
            fields=[
                ('gvw_id', models.AutoField(primary_key=True, serialize=False)),
                ('gvw_text', models.CharField(max_length=150, null=True)),
                ('gvw_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyShopVehicleConfigsModel',
            fields=[
                ('myshop_vehicle_config_id', models.AutoField(primary_key=True, serialize=False)),
                ('myshop_year_id', models.IntegerField(null=True)),
                ('myshop_make_id', models.IntegerField(null=True)),
                ('myshop_model_id', models.IntegerField(null=True)),
                ('myshop_submodel_id', models.IntegerField(null=True)),
                ('myshop_bodystyle_id', models.IntegerField(null=True)),
                ('myshop_engine_id', models.IntegerField(null=True)),
                ('myshop_brake_id', models.IntegerField(null=True)),
                ('myshop_transmission_id', models.IntegerField(null=True)),
                ('myshop_GVW_id', models.IntegerField(null=True)),
                ('myshop_drive_id', models.IntegerField(null=True)),
                ('myshop_vehicle_config_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionsModel',
            fields=[
                ('transmission_id', models.AutoField(primary_key=True, serialize=False)),
                ('transmission_type', models.CharField(blank=True, max_length=100, null=True)),
                ('tranmission_manufacturer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('transmission_control_type', models.CharField(blank=True, max_length=100, null=True)),
                ('tranmission_is_electronic_controlled', models.BooleanField(default=0)),
                ('transmission_number_of_speed', models.IntegerField(null=True)),
                ('transmission_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'transmission',
                'verbose_name_plural': 'transmissions',
                'db_table': 'transmissions_new_03',
                'ordering': ['-transmission_id'],
            },
        ),
        migrations.CreateModel(
            name='VehicleConfigMyShopConfigsModel',
            fields=[
                ('vehicle_config_id', models.AutoField(primary_key=True, serialize=False)),
                ('myshop_vehicle_config_id', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'vehicleconfigmyshopconfig',
                'verbose_name_plural': 'vehicleconfigmyshopconfigs',
                'db_table': 'vehicleconfigmyshopconfigs_new_03',
                'ordering': ['-vehicle_config_id'],
            },
        ),
    ]
