# Generated by Django 4.1.5 on 2023-04-14 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0048_brakesmodel_enginesmodel_gvwsmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyStylesModel',
            fields=[
                ('body_style_id', models.AutoField(primary_key=True, serialize=False)),
                ('body_style_name', models.CharField(max_length=150, null=True)),
                ('body_style_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'bodystyle',
                'verbose_name_plural': 'bodystyles',
                'db_table': 'bodystyles_new_03',
                'ordering': ['-body_style_id'],
            },
        ),
        migrations.CreateModel(
            name='DrivesModel',
            fields=[
                ('drive_id', models.AutoField(primary_key=True, serialize=False)),
                ('drive_type', models.CharField(max_length=150, null=True)),
                ('drive_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'drive',
                'verbose_name_plural': 'drives',
                'db_table': 'drives_new_03',
                'ordering': ['-drive_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='gvwsmodel',
            options={'ordering': ['-gvw_id'], 'verbose_name': 'gvw', 'verbose_name_plural': 'gvws'},
        ),
        migrations.AlterModelOptions(
            name='myshopvehicleconfigsmodel',
            options={'ordering': ['-myshop_vehicle_config_id'], 'verbose_name': 'myshopvehicleconfig', 'verbose_name_plural': 'myshopvehicleconfigs'},
        ),
        migrations.RemoveField(
            model_name='myshopvehicleconfigsmodel',
            name='myshop_drive_id',
        ),
        migrations.AddField(
            model_name='vehicleconfigmyshopconfigsmodel',
            name='vehicle_config_myshop_config_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='myshopvehicleconfigsmodel',
            name='myshop_GVW_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myshop_gvws', to='homepageapp.gvwsmodel'),
        ),
        migrations.AlterField(
            model_name='myshopvehicleconfigsmodel',
            name='myshop_brake_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myshop_brakes', to='homepageapp.brakesmodel'),
        ),
        migrations.AlterField(
            model_name='myshopvehicleconfigsmodel',
            name='myshop_engine_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myshop_engines', to='homepageapp.enginesmodel'),
        ),
        migrations.AlterField(
            model_name='myshopvehicleconfigsmodel',
            name='myshop_make_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myshop_makes', to='homepageapp.makesnewsql02model'),
        ),
        migrations.AlterField(
            model_name='myshopvehicleconfigsmodel',
            name='myshop_model_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myshop_models', to='homepageapp.modelsnewsql02model'),
        ),
        migrations.AlterField(
            model_name='myshopvehicleconfigsmodel',
            name='myshop_transmission_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myshop_transmission', to='homepageapp.transmissionsmodel'),
        ),
        migrations.AlterField(
            model_name='vehicleconfigmyshopconfigsmodel',
            name='myshop_vehicle_config_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepageapp.myshopvehicleconfigsmodel'),
        ),
        migrations.AlterModelTable(
            name='gvwsmodel',
            table='gvws_new_03',
        ),
        migrations.AlterModelTable(
            name='myshopvehicleconfigsmodel',
            table='myshopvehicleconfigs_new_03',
        ),
        migrations.CreateModel(
            name='SubmodelsModel',
            fields=[
                ('submodel_id', models.AutoField(primary_key=True, serialize=False)),
                ('submodel_name', models.CharField(max_length=150, null=True)),
                ('submodel_DMV_id', models.IntegerField(null=True)),
                ('submodel_created_at', models.DateTimeField(auto_now_add=True)),
                ('submodel_model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepageapp.modelsnewsql02model')),
            ],
            options={
                'verbose_name': 'submodel',
                'verbose_name_plural': 'submodels',
                'db_table': 'submodels_new_03',
                'ordering': ['-submodel_id'],
            },
        ),
        migrations.AddField(
            model_name='myshopvehicleconfigsmodel',
            name='myshop_drives',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepageapp.drivesmodel'),
        ),
        migrations.AlterField(
            model_name='myshopvehicleconfigsmodel',
            name='myshop_bodystyle_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myshop_bodystyles', to='homepageapp.bodystylesmodel'),
        ),
        migrations.AlterField(
            model_name='myshopvehicleconfigsmodel',
            name='myshop_submodel_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myshop_submodels', to='homepageapp.submodelsmodel'),
        ),
    ]
