# Generated by Django 4.1.5 on 2023-04-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0049_bodystylesmodel_drivesmodel_alter_gvwsmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitemsnewsql02model',
            name='line_item_labor_only_sale',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lineitemsnewsql02model',
            name='line_item_labor_sale',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lineitemsnewsql02model',
            name='line_item_package_sale',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lineitemsnewsql02model',
            name='line_item_part_only_sale',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lineitemsnewsql02model',
            name='line_item_part_sale',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lineitemsnewsql02model',
            name='line_item_sublet_sale',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lineitemsnewsql02model',
            name='line_item_tire_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
