# Generated by Django 4.1.5 on 2023-04-15 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0050_alter_lineitemsnewsql02model_line_item_labor_only_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleconfigmyshopconfigsmodel',
            name='myshop_vehicle_config_id',
        ),
        migrations.DeleteModel(
            name='MyShopVehicleConfigsModel',
        ),
        migrations.DeleteModel(
            name='VehicleConfigMyShopConfigsModel',
        ),
    ]
