# Generated by Django 4.1.5 on 2023-04-15 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0051_remove_vehicleconfigmyshopconfigsmodel_myshop_vehicle_config_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enginesmodel',
            old_name='engine_displacement_Liter',
            new_name='engine_displacement_liter',
        ),
    ]
