# Generated by Django 4.1.5 on 2023-04-15 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0052_rename_engine_displacement_liter_enginesmodel_engine_displacement_liter'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyShopVehicleConfigsModel',
            fields=[
                ('myshop_vehicle_config_id', models.AutoField(primary_key=True, serialize=False)),
                ('myshop_year_id', models.IntegerField(null=True)),
                ('myshop_vehicle_config_created_at', models.DateTimeField(auto_now_add=True)),
                ('myshop_GVW_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myshop_gvws', to='homepageapp.gvwsmodel')),
                ('myshop_bodystyle_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myshop_bodystyles', to='homepageapp.bodystylesmodel')),
                ('myshop_brake_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myshop_brakes', to='homepageapp.brakesmodel')),
                ('myshop_drives', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepageapp.drivesmodel')),
                ('myshop_engine_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myshop_engines', to='homepageapp.enginesmodel')),
                ('myshop_make_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myshop_makes', to='homepageapp.makesnewsql02model')),
                ('myshop_model_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myshop_models', to='homepageapp.modelsnewsql02model')),
                ('myshop_submodel_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myshop_submodels', to='homepageapp.submodelsmodel')),
                ('myshop_transmission_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myshop_transmission', to='homepageapp.transmissionsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleConfigMyShopConfigsModel',
            fields=[
                ('vehicle_config_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_config_myshop_config_created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('myshop_vehicle_config_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepageapp.myshopvehicleconfigsmodel')),
            ],
            options={
                'verbose_name': 'vehicleconfigmyshopconfig',
                'verbose_name_plural': 'vehicleconfigmyshopconfigs',
                'db_table': 'vehicleconfigmyshopconfigs_new_03',
                'ordering': ['-vehicle_config_id'],
            },
        ),
    ]
