# Generated by Django 4.1.5 on 2023-04-15 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0053_myshopvehicleconfigsmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gvwsmodel',
            options={},
        ),
        migrations.AlterModelTable(
            name='gvwsmodel',
            table=None,
        ),
    ]
