# Generated by Django 4.1.5 on 2023-04-15 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0054_alter_gvwsmodel_options_alter_gvwsmodel_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myshopvehicleconfigsmodel',
            options={'ordering': ['-myshop_vehicle_config_id'], 'verbose_name': 'myshopvehicleconfig', 'verbose_name_plural': 'myshopvehicleconfigs'},
        ),
        migrations.AlterModelTable(
            name='myshopvehicleconfigsmodel',
            table='myshopvehicleconfigs_new_03',
        ),
    ]
