# Generated by Django 4.1.5 on 2023-04-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0055_alter_myshopvehicleconfigsmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginesmodel',
            name='engine_vin_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
