# Generated by Django 4.1.5 on 2023-04-15 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0056_alter_enginesmodel_engine_vin_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gvwsmodel',
            options={'ordering': ['-gvw_id'], 'verbose_name': 'gvw', 'verbose_name_plural': 'gvws'},
        ),
        migrations.RenameField(
            model_name='submodelsmodel',
            old_name='submodel_model_id',
            new_name='submodel_model',
        ),
        migrations.AlterModelTable(
            name='gvwsmodel',
            table='gvws_new_03',
        ),
    ]
