# Generated by Django 4.1.5 on 2023-04-15 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0057_alter_gvwsmodel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myshopvehicleconfigsmodel',
            old_name='myshop_GVW_id',
            new_name='myshop_GVW',
        ),
        migrations.RenameField(
            model_name='myshopvehicleconfigsmodel',
            old_name='myshop_bodystyle_id',
            new_name='myshop_bodystyle',
        ),
        migrations.RenameField(
            model_name='myshopvehicleconfigsmodel',
            old_name='myshop_brake_id',
            new_name='myshop_brake',
        ),
        migrations.RenameField(
            model_name='myshopvehicleconfigsmodel',
            old_name='myshop_engine_id',
            new_name='myshop_engine',
        ),
        migrations.RenameField(
            model_name='myshopvehicleconfigsmodel',
            old_name='myshop_make_id',
            new_name='myshop_make',
        ),
        migrations.RenameField(
            model_name='myshopvehicleconfigsmodel',
            old_name='myshop_model_id',
            new_name='myshop_model',
        ),
        migrations.RenameField(
            model_name='myshopvehicleconfigsmodel',
            old_name='myshop_submodel_id',
            new_name='myshop_submodel',
        ),
        migrations.RenameField(
            model_name='myshopvehicleconfigsmodel',
            old_name='myshop_transmission_id',
            new_name='myshop_transmission',
        ),
    ]
