# Generated by Django 4.1.5 on 2023-04-15 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0058_rename_myshop_gvw_id_myshopvehicleconfigsmodel_myshop_gvw_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleconfigmyshopconfigsmodel',
            old_name='myshop_vehicle_config_id',
            new_name='myshop_vehicle_config',
        ),
    ]
