# Generated by Django 4.1.5 on 2023-04-15 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0059_rename_myshop_vehicle_config_id_vehicleconfigmyshopconfigsmodel_myshop_vehicle_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleconfigmyshopconfigsmodel',
            name='myshop_vehicle_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepageapp.myshopvehicleconfigsmodel'),
        ),
    ]
