# Generated by Django 4.1.5 on 2023-04-16 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0060_alter_vehicleconfigmyshopconfigsmodel_myshop_vehicle_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myshopvehicleconfigsmodel',
            name='myshop_transmission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myshop_transmissions', to='homepageapp.transmissionsmodel'),
        ),
    ]
