# Generated by Django 4.1.5 on 2023-04-16 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0061_alter_myshopvehicleconfigsmodel_myshop_transmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextMessagesModel',
            fields=[
                ('text_message_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_body', models.CharField(blank=True, max_length=4000, null=True)),
                ('text_external_id', models.BigIntegerField(null=True)),
                ('text_type', models.IntegerField()),
                ('text_to_phonenumber', models.CharField(max_length=15)),
                ('text_direction', models.BooleanField(default=False)),
                ('text_status', models.IntegerField()),
                ('text_error_message', models.CharField(max_length=255, null=True)),
                ('text_error_code', models.CharField(max_length=255, null=True)),
                ('text_datetime', models.DateTimeField()),
                ('text_body_size', models.IntegerField()),
                ('text_created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('text_last_updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('text_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepageapp.customersnewsql02model')),
            ],
            options={
                'verbose_name': 'textmessage',
                'verbose_name_plural': 'textmessages',
                'db_table': 'textmessages_new_03',
                'ordering': ['-text_message_id'],
            },
        ),
    ]
