# Generated by Django 4.1.5 on 2023-04-17 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0062_textmessagesmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclesnewsql02model',
            name='vehicle_GVW_id',
        ),
        migrations.RemoveField(
            model_name='vehiclesnewsql02model',
            name='vehicle_body_style_id',
        ),
        migrations.RemoveField(
            model_name='vehiclesnewsql02model',
            name='vehicle_brake_id',
        ),
        migrations.RemoveField(
            model_name='vehiclesnewsql02model',
            name='vehicle_drive_type_id',
        ),
        migrations.RemoveField(
            model_name='vehiclesnewsql02model',
            name='vehicle_engine_id',
        ),
        migrations.RemoveField(
            model_name='vehiclesnewsql02model',
            name='vehicle_make_id',
        ),
        migrations.RemoveField(
            model_name='vehiclesnewsql02model',
            name='vehicle_phone_id',
        ),
        migrations.RemoveField(
            model_name='vehiclesnewsql02model',
            name='vehicle_sub_model_id',
        ),
        migrations.RemoveField(
            model_name='vehiclesnewsql02model',
            name='vehicle_transmission_id',
        ),
        migrations.AddField(
            model_name='vehiclesnewsql02model',
            name='vehicle_GVW',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepageapp.gvwsmodel'),
        ),
        migrations.AddField(
            model_name='vehiclesnewsql02model',
            name='vehicle_body_style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_bodystyles', to='homepageapp.bodystylesmodel'),
        ),
        migrations.AddField(
            model_name='vehiclesnewsql02model',
            name='vehicle_brake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_brakes', to='homepageapp.brakesmodel'),
        ),
        migrations.AddField(
            model_name='vehiclesnewsql02model',
            name='vehicle_drive_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_drives', to='homepageapp.drivesmodel'),
        ),
        migrations.AddField(
            model_name='vehiclesnewsql02model',
            name='vehicle_engine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_engines', to='homepageapp.enginesmodel'),
        ),
        migrations.AddField(
            model_name='vehiclesnewsql02model',
            name='vehicle_make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_makes', to='homepageapp.makesnewsql02model'),
        ),
        migrations.AddField(
            model_name='vehiclesnewsql02model',
            name='vehicle_phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepageapp.phonesnewsql02model'),
        ),
        migrations.AddField(
            model_name='vehiclesnewsql02model',
            name='vehicle_sub_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_submodels', to='homepageapp.submodelsmodel'),
        ),
        migrations.AddField(
            model_name='vehiclesnewsql02model',
            name='vehicle_transmission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_transmissions', to='homepageapp.enginesmodel'),
        ),
    ]
