# Generated by Django 4.1.5 on 2023-04-17 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0063_remove_vehiclesnewsql02model_vehicle_gvw_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partitemmodel',
            name='part_item_part_id',
        ),
        migrations.AddField(
            model_name='partitemmodel',
            name='part_item_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepageapp.partsmodel'),
        ),
        migrations.AlterField(
            model_name='noteitemsnewsql02model',
            name='note_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='noteitemsnewsql02model',
            name='tech_observation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='partitemmodel',
            name='part_item_meta',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
