# Generated by Django 4.1.5 on 2023-04-17 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0064_remove_partitemmodel_part_item_part_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclesnewsql02model',
            name='vehicle_GVW',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_gvws', to='homepageapp.gvwsmodel'),
        ),
        migrations.AlterField(
            model_name='vehiclesnewsql02model',
            name='vehicle_phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_phones', to='homepageapp.phonesnewsql02model'),
        ),
    ]
