# Generated by Django 4.1.5 on 2023-04-17 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0065_alter_vehiclesnewsql02model_vehicle_gvw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitemmodel',
            name='part_item_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_parts', to='homepageapp.partsmodel'),
        ),
    ]
