# Generated by Django 4.1.5 on 2023-04-17 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0066_alter_partitemmodel_part_item_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessagesmodel',
            name='text_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_customers', to='homepageapp.customersnewsql02model'),
        ),
    ]
