# Generated by Django 4.1.5 on 2023-04-18 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0067_alter_textmessagesmodel_text_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleconfigmyshopconfigsmodel',
            name='myshop_vehicle_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicleconfigmyshopconfigs', to='homepageapp.myshopvehicleconfigsmodel'),
        ),
    ]
