# Generated by Django 4.1.5 on 2023-04-18 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0068_alter_vehicleconfigmyshopconfigsmodel_myshop_vehicle_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonesnewsql02model',
            name='phone_desc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_descs', to='homepageapp.phonedescmodel'),
        ),
    ]
