# Generated by Django 4.1.5 on 2023-04-18 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0069_alter_phonesnewsql02model_phone_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclesnewsql02model',
            name='vehicle_transmission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_transmissions', to='homepageapp.transmissionsmodel'),
        ),
    ]
