# Generated by Django 4.1.5 on 2023-04-18 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0070_alter_vehiclesnewsql02model_vehicle_transmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclesnewsql02model',
            name='vehicle_cust_id',
        ),
        migrations.AddField(
            model_name='vehiclesnewsql02model',
            name='vehicle_cust',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_customers', to='homepageapp.customersnewsql02model'),
        ),
    ]
