# Generated by Django 4.1.5 on 2023-04-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0071_remove_vehiclesnewsql02model_vehicle_cust_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboritemmodel',
            name='labor_item_is_come_back_invoice',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
