# Generated by Django 4.1.5 on 2023-04-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0072_alter_laboritemmodel_labor_item_is_come_back_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboritemmodel',
            name='labor_item_symptom',
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
