# Generated by Django 4.1.5 on 2023-04-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0073_alter_laboritemmodel_labor_item_symptom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboritemmodel',
            name='labor_item_work_performed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
