# Generated by Django 4.1.5 on 2023-04-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0074_alter_laboritemmodel_labor_item_work_performed'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceStatusModel',
            fields=[
                ('invoice_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_status_description', models.CharField(max_length=30, null=True)),
                ('invoice_status_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'invoicestatus',
                'verbose_name_plural': 'invoicestatuses',
                'db_table': 'invoicestatuess_new_03',
                'ordering': ['invoice_status_id'],
            },
        ),
    ]
