# Generated by Django 4.1.5 on 2023-04-19 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0075_invoicestatusmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentsmodel',
            old_name='payment_account_class_id',
            new_name='payment_account_class',
        ),
        migrations.RenameField(
            model_name='paymentsmodel',
            old_name='payment_customer_id',
            new_name='payment_customer',
        ),
        migrations.RenameField(
            model_name='paymentsmodel',
            old_name='payment_transcation_id',
            new_name='payment_transcation',
        ),
        migrations.AlterField(
            model_name='paymentsmodel',
            name='payment_invoice_status_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepageapp.invoicestatusmodel'),
        ),
    ]
