# Generated by Django 4.1.5 on 2023-04-19 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0077_rename_payment_repair_order_id_paymentsmodel_payment_repair_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentsmodel',
            old_name='payment_invoice_status_id',
            new_name='payment_invoice_status',
        ),
    ]
