# Generated by Django 4.1.5 on 2023-04-19 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0078_rename_payment_invoice_status_id_paymentsmodel_payment_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsmodel',
            name='payment_account_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_accountclasses', to='homepageapp.accountclassmodel'),
        ),
        migrations.AlterField(
            model_name='paymentsmodel',
            name='payment_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_customers', to='homepageapp.customersnewsql02model'),
        ),
        migrations.AlterField(
            model_name='paymentsmodel',
            name='payment_invoice_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_invoicestatuses', to='homepageapp.invoicestatusmodel'),
        ),
        migrations.AlterField(
            model_name='paymentsmodel',
            name='payment_repair_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_repairorders', to='homepageapp.repairordersnewsql02model'),
        ),
        migrations.AlterField(
            model_name='paymentsmodel',
            name='payment_transcation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='homepageapp.paymenttransactionsmodel'),
        ),
    ]
