# Generated by Django 4.1.5 on 2023-06-04 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0079_alter_paymentsmodel_payment_account_class_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noteitemsnewsql02model',
            old_name='is_printed_on_order',
            new_name='note_item_is_printed_on_order',
        ),
        migrations.RenameField(
            model_name='noteitemsnewsql02model',
            old_name='note_text',
            new_name='note_item_tech_observation',
        ),
        migrations.RenameField(
            model_name='noteitemsnewsql02model',
            old_name='tech_observation',
            new_name='note_item_text',
        ),
        migrations.RemoveField(
            model_name='orderrevisionnewsql02model',
            name='order_revision_repair_order_id',
        ),
        migrations.AddField(
            model_name='orderrevisionnewsql02model',
            name='order_revision_repair_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderrevisions', to='homepageapp.repairordersnewsql02model'),
        ),
    ]
