# Generated by Django 4.1.5 on 2023-06-14 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0080_rename_is_printed_on_order_noteitemsnewsql02model_note_item_is_printed_on_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitemsnewsql02model',
            name='line_item_account_class_id',
        ),
        migrations.RemoveField(
            model_name='partsmodel',
            name='part_account_class_id',
        ),
        migrations.AddField(
            model_name='lineitemsnewsql02model',
            name='line_item_account_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineitem_accountclasses', to='homepageapp.accountclassmodel'),
        ),
        migrations.AddField(
            model_name='partsmodel',
            name='part_account_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_accountclasses', to='homepageapp.accountclassmodel'),
        ),
        migrations.AlterField(
            model_name='customersnewsql02model',
            name='customer_fleet_vendor_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
