# Generated by Django 4.1.5 on 2023-06-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0081_remove_lineitemsnewsql02model_line_item_account_class_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonesnewsql02model',
            name='phone_number_digits_only',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
