# Generated by Django 4.1.5 on 2023-06-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0084_rename_repair_order_serviced_vehcle_engine_hours_in_repairordersnewsql02model_repair_order_serviced_'),
    ]

    operations = [
        migrations.AddField(
            model_name='cannedjobsnewsql02model',
            name='canned_job_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
