# Generated by Django 4.1.5 on 2023-07-10 02:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirebaseUser',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firebase_user_id', models.BigIntegerField()),
                ('firebase_user_uid', models.CharField(max_length=100, null=True)),
                ('firebase_user_display_name', models.CharField(max_length=200, null=True)),
                ('firebase_user_email', models.EmailField(max_length=254, null=True)),
                ('firebase_user_email_is_verified', models.BooleanField(default=False)),
                ('firebase_user_phone_number', models.CharField(max_length=20, null=True)),
                ('firebase_user_photo_url', models.CharField(max_length=1000, null=True)),
                ('firebase_user_password', models.CharField(max_length=254, null=True)),
                ('firebase_user_disabled', models.BooleanField(default=False)),
                ('firebase_user_providers', models.CharField(max_length=200, null=True)),
                ('firebase_user_created_at', models.DateTimeField(auto_now_add=True)),
                ('firebase_user_at_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'firebaseuser',
                'verbose_name_plural': 'firebaseusers',
                'db_table': 'firebaseuser_management',
                'ordering': ['-firebase_user_id'],
            },
        ),
    ]
