# Generated by Django 4.1.5 on 2023-06-10 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firebase_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firebaseuser',
            old_name='frebase_user_uid',
            new_name='firebase_user_uid',
        ),
    ]
