# Generated by Django 4.1.5 on 2023-06-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firebase_auth_app', '0002_rename_frebase_user_uid_firebaseuser_firebase_user_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firebaseuser',
            old_name='firebase_user_uid',
            new_name='firebase_user_uuid',
        ),
    ]
