# Generated by Django 4.1.5 on 2023-06-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase_auth_app', '0003_rename_firebase_user_uid_firebaseuser_firebase_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebaseuser',
            name='firebase_user_uid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
