# Generated by Django 4.1.5 on 2023-06-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firebase_auth_app', '0004_firebaseuser_firebase_user_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firebaseuser',
            old_name='firebase_user_uuid',
            new_name='uuid',
        ),
    ]
