# Generated by Django 4.1.5 on 2023-06-11 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('firebase_auth_app', '0005_rename_firebase_user_uuid_firebaseuser_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebaseuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
