apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  labels:
    io.kompose.service: celery
  name: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: celery
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (HEAD)
      labels:
        io.kompose.network/new-76prolubepluscom-default: "true"
        io.kompose.service: celery
    spec:
      containers:
        - args:
            - celery
            - -A
            - automanshop
            - worker
            - --loglevel=info
          image: celery
          name: celery
          resources: {}
          # volumeMounts:
          #   - mountPath: /app
          #     name: celery-claim0
      restartPolicy: Always
      # volumes:
      #   - name: celery-claim0
      #     persistentVolumeClaim:
      #       claimName: celery-claim0
status: {}
