version: "3.10"

services:
  web:
    build: .
    command:
      ["daphne", "-b", "0.0.0.0", "-p", "8000", "automanshop.asgi:application"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_PROD_ENV=${DJANGO_PROD_ENV}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - RECAPTCHA_PUBLIC_KEY=${RECAPTCHA_PUBLIC_KEY}
      - RECAPTCHA_PRIVATE_KEY=${RECAPTCHA_PRIVATE_KEY}
      - EMAIL_SENDER=${EMAIL_SENDER}
      - EMAIL_SENDER_PWD=${EMAIL_SENDER_PWD}
      - EMAIL_VERIFICATION_API_KEY=${EMAIL_VERIFICATION_API_KEY}
      - GOOGLE_CREDENTIAL_PATH=${GOOGLE_CREDENTIAL_PATH}
      - CLOUDSQL_DB_USER=${CLOUDSQL_DB_USER}
      - CLOUDSQL_DB_SERVER=${CLOUDSQL_DB_SERVER}
      - CLOUDSQL_DB_PORT=${CLOUDSQL_DB_PORT}
      - CLOUDSQL_DB_PASSWORD=${CLOUDSQL_DB_PASSWORD}
      - CLOUDSQL_DB_DATABASE1=${CLOUDSQL_DB_DATABASE1}
      - CLOUDSQL_DB_DATABASE2=${CLOUDSQL_DB_DATABASE2}
      - SQL_DOCKERIZED=${SQL_DOCKERIZED}
      - SQL_DOCKERIZED_HOST=${SQL_DOCKERIZED_HOST}
      - DB_SERVER=${DB_SERVER}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE1=${DB_DATABASE1}
      - DB_DATABASE2=${DB_DATABASE2}
      - DEMO_DB_DATABASE_NAME=${DEMO_DB_DATABASE_NAME}
      - DB_SA_USER=${DB_SA_USER}
      - DB_SA_USER_PASSWORD=${DB_SA_USER_PASSWORD}
      - DB_APP_USR=${DB_APP_USR}
      - DB_APP_USER_PASSWORD=${DB_APP_USER_PASSWORD}
      - AZURE_DB_SERVER=${AZURE_DB_SERVER}
      - AZURE_DB_USER=${AZURE_DB_USER}
      - AZURE_DB_PORT=${AZURE_DB_PORT}
      - AZURE_DB_PASSWORD=${AZURE_DB_PASSWORD}
      - AZURE_DB_DATABASE=${AZURE_DB_DATABASE}
      - EAB_KEY_ID=${EAB_KEY_ID}
      - EAB_HMAC_KEY=${EAB_HMAC_KEY}
      - ACME_API_TOKEN=${ACME_API_TOKEN}
      - PLATE2VIN_API_KEY=${PLATE2VIN_API_KEY}
      - STRIPE_PUBLIC_TEST_KEY=${STRIPE_PUBLIC_TEST_KEY}
      - STRIPE_SECRET_TEST_KEY=${STRIPE_SECRET_TEST_KEY}
      - STRIPE_PUBLIC_LIVE_KEY=${STRIPE_PUBLIC_LIVE_KEY}
      - STRIPE_SECRET_LIVE_KEY=${STRIPE_SECRET_LIVE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_KEY2=${OPENAI_API_KEY2}
      - REDIS_DOCKERIZED=${REDIS_DOCKERIZED}
      - REDIS_DOCKERIZED_HOST=${REDIS_DOCKERIZED_HOST}
      - USE_LOCAL_REDIS=${USE_LOCAL_REDIS}
      - LOCAL_REDIS_HOST=${LOCAL_REDIS_HOST}
      - LOCAL_REDIS_PORT=${LOCAL_REDIS_PORT}
      - LOCAL_REDIS_PASSWORD=${LOCAL_REDIS_PASSWORD}
      - LOCAL_REDIS_USE_SSL=${LOCAL_REDIS_USE_SSL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USE_SSL=${REDIS_USE_SSL}
    # depends_on:
    #   - web-secret
    # - sqldb
    # - redis

  celery:
    build: .
    command: celery -A automanshop worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web

      # - redis

  # beat:
  #   build: .
  #   command: celery -A automanshop  beat --loglevel=info
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - celery
  # - redis
  # volumes:
  # - sql_data:/var/opt/mssql
  # - /Users/stephenwang/Documents/myiCloudCopy-76ProLubePlus/13-Information-Technology/003-IT_New-Site-Development-2022/05_databases/sqldata:/var/opt/mssql

  #       # Add other necessary environment variables for SQL Server
  # volumes:
  #   sql_data:
