name: /Users/stephenwang/Documents/76prolubeplus.com
channels:
  - conda-forge 
  - nodefaults
#prefix: /Users/stephenwang/Documents/76prolubeplus.com
dependencies:
  # - django
  # - pandas
  #- scipy
  #  - curl
  #- requests
  #- bokeh> 0.9.2
  #- numpy
  # - nodejs>0.10
  #- flask
  - python >=3.9
  #- markdown
  #- mysql-python
 # - djangorestframework. # django rest API framework
 # - django-filter
 # -  python-dotenv  -- this package was intalled on 2022-10-28 so that the application can grab envrionemen variables in the '.env' file.
