apiVersion: v1
kind: Service
metadata:
  annotations:
    version: v1
    description: 'use-2022-sql-server-image'
  labels:
    io.kompose.service: sqldb
  name: sqldb-deployment
spec:
  ports:
    - name: "1433"
      port: 1433
      targetPort: 1433
  selector:
    io.kompose.service: sqldb
status:
  loadBalancer: {}
