apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
        - args:
            - celery
            - -A
            - automanshop
            - beat
            - --loglevel=info
          image: holleratme420/web:v1
          name: beat
          resources: {}
          # volumeMounts:
          #   - mountPath: /app
          #     name: beat-claim0
      restartPolicy: Always
      # volumes:
      #   - name: beat-claim0
          # persistentVolumeClaim:
          #   claimName: beat-claim0
status: {}
