from .employment_info import EmploymentInfoForm
from .personal_contact_info import PersonalContactInfoForm
from .remarks_and_comments import RemarkAndCommentsForm
from .talent_create_forms import TALENT_CREATE_FORMS
from .talent_update import TalentUpdateForm
from .talent_create import TalentCreateForm
from .talent_document import TalentDocumentForm