# Generated by Django 4.1.5 on 2023-05-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internaluser',
            old_name='last_updated_at',
            new_name='user_last_updated_at',
        ),
        migrations.AlterField(
            model_name='internaluser',
            name='user_auth_group',
            field=models.PositiveSmallIntegerField(choices=[(0, 'visitor: ready-only'), (0, 'customer-group'), (2, 'internal-user-group'), (3, 'talent-management-group'), (4, 'accounting-group'), (5, 'it-group'), (6, 'manager-group'), (7, 'boardmember-group'), (88, 'master-shi-fu-group')], default=0),
        ),
    ]
