# Generated by Django 4.1.5 on 2023-05-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_users', '0002_rename_last_updated_at_internaluser_user_last_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaluser',
            name='user_talent_profile_last_linked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internaluser',
            name='user_talent_profile_linkage_is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
