# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: coredns-custom
#   namespace: kube-system
# data:
#   test.server: |
#     <domain to be rewritten>.com:53 {
#     log
#     errors
#     rewrite stop {
#       name regex (.*)\.<domain to be rewritten>.com {1}.default.svc.cluster.local
#       answer name (.*)\.default\.svc\.cluster\.local {1}.<domain to be rewritten>.com
#     }
#     forward . /etc/resolv.conf # you can redirect this to a specific DNS server such as 10.0.0.10, but that server must be able to resolve the rewritten domain name
#     }