from .base import csrf_exempt, HttpResponse, stripe, settings

@csrf_exempt
def stripe_webhook(request):
    
    # settings.STRIPE_WEBHOOK_SECRET 
    if settings.DEBUG and settings.DJANGO_PROD_ENV == False:    
        endpoint_secret = settings.STRIPE_WEBHOOK_SECRET_LOCAL or \
                        input('Enter the local webook secret generated by Stripe CLI...') 
                            #"whsec_9fc3fe3c0a22d70e9d62a1b89b6e0abe158aa5c4c8a769b965c78bf422e7219c"
    else:
        endpoint_secret = settings.STRIPE_WEBHOOK_TEST_SECRET 
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None
    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, endpoint_secret,
            # settings.STRIPE_WEBHOOK_SECRET
        )
    except ValueError as e:
        #Invlaid Payload

        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
            # Invalid signature
        return HttpResponse(status=400)
    

    # Passed signature verification
    return HttpResponse(status=200)
