# [START django_app]
runtime: python39

# env_variables:
#           DJANGO_SETTINGS_MODULE: "myapp.settings"

entrypoint:
  gunicorn --config ../gunicorn/gunicorn_conf_dev_20230712.py prolube76site.wsgi:application
handlers:
# Tel GAE where are Django static assets located
- url: /static
  static_dir: static/
# Route everything else to the main app
- url: /.*
  script: auto
# [END django_app]