# Generated by Django 4.1.5 on 2023-04-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('appointment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('appointment_requested_datetime', models.DateTimeField(blank=True)),
                ('appointment_reason_for_visit', models.CharField(max_length=255)),
                ('appointment_first_name', models.CharField(max_length=50)),
                ('appointment_last_name', models.CharField(max_length=50)),
                ('appointment_user_uid', models.CharField(blank=True, max_length=50, null=True)),
                ('appointment_email', models.EmailField(max_length=254)),
                ('appointment_vehicle_detail', models.TextField()),
                ('appointment_concern_description', models.TextField(blank=True)),
                ('appointment_status', models.CharField(choices=[('U', 'Not Submitted'), ('P', 'Pending'), ('C', 'Confirmed'), ('R', 'Rejected'), ('S', 'Rescheduled')], default='U', max_length=1)),
                ('appointment_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
