# Generated by Django 4.1.5 on 2023-07-10 04:10

import core_operations.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_users', '0001_initial'),
        ('homepageapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('appointment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('appointment_requested_datetime', models.DateTimeField()),
                ('appointment_reason_for_visit', models.PositiveSmallIntegerField(choices=[(0, '00-not selected.'), (1, '01-oil change and maintenance'), (2, '02-a/c diagnosis, compressors etc.'), (3, '03-brakes, transmission'), (4, '04-service lights, engine related'), (5, '05-other reasons')], default=0)),
                ('appointment_first_name', models.CharField(max_length=50, null=True)),
                ('appointment_last_name', models.CharField(max_length=50, null=True)),
                ('appointment_phone_number', core_operations.models.FormattedPhoneNumberField(blank=True, max_length=15, null=True)),
                ('appointment_phone_number_digits_only', models.CharField(max_length=20, null=True)),
                ('appointment_user_type', models.CharField(blank=True, max_length=50, null=True)),
                ('appointment_email', models.EmailField(max_length=254, null=True)),
                ('appointment_vehicle_year', models.CharField(blank=True, max_length=4, null=True)),
                ('appointment_vehicle_make', models.CharField(blank=True, max_length=100, null=True)),
                ('appointment_vehicle_model', models.CharField(blank=True, max_length=100, null=True)),
                ('appointment_vehicle_license_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('appointment_vehicle_license_state', models.CharField(blank=True, max_length=2, null=True)),
                ('appointment_vehilce_vin_number', models.CharField(blank=True, max_length=30, null=True)),
                ('appointment_vehicle_detail', models.TextField()),
                ('appointment_vehicle_detail_in_json', models.CharField(max_length=4000, null=True)),
                ('appointment_concern_description', models.TextField(blank=True)),
                ('appointment_status', models.CharField(choices=[(0, '00_Not_Submitted'), (1, '01_Pending'), (2, '02_Confirmed'), (3, '03_Rejected'), (4, '04_Rescheduled'), (5, '05_Progressing'), (10, '10_Completed'), (20, '20_Cancelled')], default=0, max_length=50)),
                ('appointment_status_comments', models.CharField(blank=True, max_length=4000, null=True)),
                ('appointment_is_active', models.BooleanField(default=True)),
                ('appointment_preferred_contact_method', models.CharField(blank=True, max_length=100, null=True)),
                ('appointment_is_converted_to_ro', models.BooleanField(default=False)),
                ('appointment_created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment_last_updated_date', models.DateTimeField(auto_now=True)),
                ('appointment_created_by_internal_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('appointment_customer_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_users.customeruser')),
                ('appointment_repair_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_repair_order', to='homepageapp.repairordersnewsql02model')),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
        migrations.CreateModel(
            name='AppointmentImages',
            fields=[
                ('image_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('appointment_image', models.FileField(upload_to='appointment_images')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('image_is_active', models.BooleanField(default=True)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_appointmentimages', to='appointments.appointmentrequest')),
            ],
            options={
                'verbose_name': 'appointment_image',
                'verbose_name_plural': 'appointment_images',
                'db_table': 'appointment_images',
                'ordering': ['-image_id'],
            },
        ),
    ]
