# Generated by Django 4.1.5 on 2023-05-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='appointment_user_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='appointment_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='appointment_last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='appointment_reason_for_visit',
            field=models.PositiveSmallIntegerField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('RESCHEDULED', 'Rescheduled'), ('PORGRESSING', 'Progressing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default=0),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='appointment_status',
            field=models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('RESCHEDULED', 'Rescheduled'), ('PORGRESSING', 'Progressing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NOT_SUBMITTED', max_length=20),
        ),
    ]
