# Generated by Django 4.1.5 on 2023-05-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointmentrequest_appointment_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='appointment_reason_for_visit',
            field=models.PositiveSmallIntegerField(choices=[(0, '00-not selected.'), (1, '01-oil change and maint.'), (2, '02-a/c related'), (3, '03-brakes, transmission'), (4, '04-service lights, engine'), (5, '05-other reasons')], default=0),
        ),
    ]
