# Generated by Django 4.1.5 on 2023-06-03 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_users', '0003_alter_customeruser_cust_user_linkage_is_confirmed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepageapp', '0079_alter_paymentsmodel_payment_account_class_and_more'),
        ('appointments', '0003_alter_appointmentrequest_appointment_reason_for_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='appointment_user_uid',
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='appointment_created_by_internal_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='appointment_customer_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_users.customeruser'),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='appointment_is_converted_to_ro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='appointment_last_updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='appointment_repair_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepageapp.repairordersnewsql02model'),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='appointment_status_comments',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='appointment_vehicle_detail_in_json',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='appointment_vehicle_make',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='appointment_vehicle_model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='appointment_vehicle_year',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='appointment_first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='appointment_status',
            field=models.CharField(choices=[('01_NOT_SUBMITTED', 'Not Submitted'), ('02_PENDING', 'Pending'), ('03_CONFIRMED', 'Confirmed'), ('04_REJECTED', 'Rejected'), ('05_RESCHEDULED', 'Rescheduled'), ('06_PORGRESSING', 'Progressing'), ('07_CANCELLED', 'Cancelled'), ('10_COMPLETED', 'Completed')], default='01_NOT_SUBMITTED', max_length=50),
        ),
        migrations.AlterModelTable(
            name='appointmentrequest',
            table='appointmentrequests',
        ),
    ]
