# Generated by Django 4.1.5 on 2023-06-03 23:28

import core_operations.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_appointmentrequest_appointment_user_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='appointment_phone_number',
            field=core_operations.models.FormattedPhoneNumberField(blank=True, max_length=15, null=True),
        ),
    ]
