# Generated by Django 4.1.5 on 2023-06-04 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointmentrequest_appointment_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentImages',
            fields=[
                ('image_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('appointment_images', models.FileField(upload_to='appointment_images')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('image_is_active', models.BooleanField(default=True)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_appointmentimages', to='appointments.appointmentrequest')),
            ],
            options={
                'db_table': 'appointment_images',
                'ordering': ['-image_id'],
            },
        ),
    ]
