# Generated by Django 4.1.5 on 2023-06-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointmentimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='appointment_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
