# Generated by Django 4.1.5 on 2023-06-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_appointmentrequest_appointment_repair_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='appointment_reason_for_visit',
            field=models.PositiveSmallIntegerField(choices=[(0, '00-not selected.'), (1, '01-oil change and maintenance'), (2, '02-a/c diagnosis, compressors etc.'), (3, '03-brakes, transmission'), (4, '04-service lights, engine related'), (5, '05-other reasons')], default=0),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='appointment_vehicle_year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
