# Generated by Django 4.1.5 on 2023-06-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_appointmentrequest_appointment_reason_for_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='appointment_requested_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='appointment_status',
            field=models.CharField(choices=[(0, '00_Not_Submitted'), (1, '01_Pending'), (2, '02_Confirmed'), (3, '03_Rejected'), (4, '04_Rescheduled'), (5, '05_Progressing'), (10, '10_Completed'), (20, '20_Cancelled')], default=0, max_length=50),
        ),
    ]
