# Generated by Django 4.1.5 on 2023-06-05 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_alter_appointmentrequest_appointment_requested_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentimages',
            old_name='appointment_images',
            new_name='appointment_image',
        ),
    ]
