# Generated by Django 4.1.5 on 2023-06-07 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_rename_appointment_images_appointmentimages_appointment_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentimages',
            options={'ordering': ['-image_id'], 'verbose_name': 'appointment_image', 'verbose_name_plural': 'appointment_images'},
        ),
    ]
