# Generated by Django 4.1.5 on 2023-06-07 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_alter_appointmentimages_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointmentrequest',
            table='appointments',
        ),
    ]
