# Generated by Django 4.1.5 on 2023-06-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_alter_appointmentrequest_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='appointment_preferred_contact_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='appointment_vehicle_license_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='appointment_vehicle_license_state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='appointment_vehilce_vin_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='appointment_status_comments',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='appointment_vehicle_make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='appointment_vehicle_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='appointment_vehicle_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
