# Generated by Django 4.1.5 on 2023-06-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_appointmentrequest_appointment_preferred_contact_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='appointment_phone_number_digits_only',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
