# Generated by Django 4.1.5 on 2023-05-01 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import talent_management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentsModel',
            fields=[
                ('talent_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('talent_employee_id', models.IntegerField(unique=True)),
                ('talent_first_name', models.CharField(max_length=50)),
                ('talent_last_name', models.CharField(max_length=50)),
                ('talent_middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('talent_preferred_name', models.CharField(blank=True, max_length=50, null=True)),
                ('talent_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('talent_phone_number_primary', talent_management.models.FormattedPhoneNumberField(blank=True, max_length=15, null=True)),
                ('talent_emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('talent_date_of_birth', models.DateField(verbose_name='your date of birth')),
                ('talent_physical_address_01', models.CharField(max_length=100, verbose_name='your street address')),
                ('talent_physical_address_02', models.CharField(blank=True, max_length=100, null=True)),
                ('talent_physical_address_city', models.CharField(max_length=50, null=True)),
                ('talent_physical_address_state', models.CharField(max_length=2, null=True)),
                ('talent_physical_address_zip_code', models.CharField(max_length=10, null=True)),
                ('talent_physical_address_country', models.CharField(default='US', max_length=50)),
                ('talent_mailing_address_is_the_same_physical_address', models.BooleanField(default=False)),
                ('talent_mailing_address_01', models.CharField(max_length=100, verbose_name='your street address')),
                ('talent_mailing_address_02', models.CharField(blank=True, max_length=100, null=True)),
                ('talent_mailing_address_city', models.CharField(max_length=50)),
                ('talent_mailing_address_state', models.CharField(max_length=2)),
                ('talent_mailing_address_zip_code', models.CharField(max_length=10)),
                ('talent_mailing_address_country', models.CharField(default='US', max_length=50)),
                ('talent_education_level', models.CharField(default='UNDEFINED', max_length=100)),
                ('talent_certifications', models.CharField(max_length=500, null=True)),
                ('talent_hire_date', models.DateTimeField(blank=True)),
                ('talent_department', models.CharField(choices=[('Unassigned', 'your deparment has not been assigned yet.'), ('service advisor', 'service advisor group'), ('service technican', 'service technican group'), ('talent management', 'talent management group'), ('legal', 'legal group'), ('visitor only', 'visitor group')], default='Unassigned', max_length=50)),
                ('talent_HR_remarks_json', models.TextField(null=True)),
                ('talent_incident_record_json', models.TextField(null=True)),
                ('talent_is_active', models.BooleanField(default=True)),
                ('talent_pay_type', models.PositiveSmallIntegerField(choices=[(0, 'unassigned pay type. Must assign before the first work day.'), (1, 'hourly'), (2, 'salaried'), (4, 'internship'), (3, 'bonus pay'), (5, 'pay type other-1'), (6, 'pay type other-2')], default=0)),
                ('talent_pay_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('talent_pay_frequency', models.CharField(max_length=50, null=True)),
                ('talent_previous_department', models.CharField(choices=[('Unassigned', 'your deparment has not been assigned yet.'), ('service advisor', 'service advisor group'), ('service technican', 'service technican group'), ('talent management', 'talent management group'), ('legal', 'legal group'), ('visitor only', 'visitor group')], default='Unassigned', max_length=50)),
                ('talent_discharge_date', models.DateTimeField(null=True)),
                ('talent_years_of_work', talent_management.models.YearsOfWorkField(decimal_places=1, max_digits=5, null=True)),
                ('talent_created_at', models.DateTimeField(auto_now_add=True)),
                ('talent_last_udpated_date', models.DateTimeField(auto_now=True)),
                ('talent_created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('talent_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='talent_management.talentsmodel')),
            ],
            options={
                'db_table': 'talent_managment',
                'ordering': ['-talent_id'],
            },
        ),
    ]
