# Generated by Django 4.1.5 on 2023-07-10 02:57

import core_operations.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentsModel',
            fields=[
                ('talent_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('talent_employee_id', models.IntegerField(unique=True)),
                ('talent_first_name', models.CharField(max_length=50)),
                ('talent_last_name', models.CharField(max_length=50)),
                ('talent_middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('talent_preferred_name', models.CharField(blank=True, max_length=50, null=True)),
                ('talent_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('talent_phone_number_primary', core_operations.models.FormattedPhoneNumberField(blank=True, max_length=15, null=True)),
                ('talent_phone_number_primary_digits_only', models.CharField(blank=True, max_length=20, null=True)),
                ('talent_phone_number_alternates_01', core_operations.models.FormattedPhoneNumberField(blank=True, max_length=15, null=True)),
                ('talent_phone_number_alternates_02', core_operations.models.FormattedPhoneNumberField(blank=True, max_length=15, null=True)),
                ('talent_emergency_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('talent_date_of_birth', models.DateField(null=True, verbose_name='your date of birth')),
                ('talent_physical_address_01', models.CharField(max_length=100, verbose_name='street address 01')),
                ('talent_physical_address_02', models.CharField(blank=True, max_length=100, null=True, verbose_name='street address 02(apt numbers, unit #, etc.)')),
                ('talent_physical_address_city', models.CharField(max_length=50, null=True)),
                ('talent_physical_address_state', models.CharField(max_length=2, null=True)),
                ('talent_physical_address_zip_code', models.CharField(max_length=10, null=True)),
                ('talent_physical_address_country', models.CharField(default='US', max_length=50)),
                ('talent_mailing_address_is_the_same_physical_address', models.BooleanField(default=True)),
                ('talent_mailing_address_01', models.CharField(max_length=100, verbose_name='mailing address 01')),
                ('talent_mailing_address_02', models.CharField(blank=True, max_length=100, null=True, verbose_name=' mailing address 02 (apt numbers, unit #, etc)')),
                ('talent_mailing_address_city', models.CharField(max_length=50, null=True)),
                ('talent_mailing_address_state', models.CharField(max_length=2, null=True)),
                ('talent_mailing_address_zip_code', models.CharField(max_length=10)),
                ('talent_mailing_address_country', models.CharField(default='US', max_length=50)),
                ('talent_education_level', models.CharField(default='None', max_length=100)),
                ('talent_certifications', models.CharField(blank=True, max_length=500, null=True)),
                ('talent_hire_date', models.DateTimeField(blank=True, null=True)),
                ('talent_department', models.CharField(choices=[('Unassigned', 'your deparment has not been assigned yet.'), ('service advisor', 'service advisor group'), ('service technican', 'service technican group'), ('talent management', 'talent management group'), ('legal', 'legal group'), ('visitor only', 'visitor group')], default='Unassigned', max_length=50)),
                ('talent_work_start_date', models.DateTimeField(blank=True, null=True)),
                ('talent_pay_type', models.PositiveSmallIntegerField(choices=[(0, 'unassigned pay type. Must be assigned before the first work day.'), (1, 'hourly'), (2, 'salaried'), (4, 'internship'), (3, 'bonus pay'), (5, 'pay type other-1'), (6, 'pay type other-2')], default=0)),
                ('talent_pay_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('talent_pay_frequency', models.PositiveSmallIntegerField(choices=[(0, 'pay frequency not defined'), (1, 'daily'), (2, 'weekly'), (3, 'bi-weekly'), (4, 'semi-monthly'), (5, 'monthly'), (6, 'monthly'), (7, 'monthly'), (8, 'reserved pay frequency 1; not used yet'), (9, 'reserved pay frequency 2; not used yet')], default=0)),
                ('talent_previous_department', models.CharField(choices=[('Unassigned', 'your deparment has not been assigned yet.'), ('service advisor', 'service advisor group'), ('service technican', 'service technican group'), ('talent management', 'talent management group'), ('legal', 'legal group'), ('visitor only', 'visitor group')], default='Unassigned', max_length=50)),
                ('talent_discharge_date', models.DateTimeField(null=True)),
                ('talent_years_of_work', core_operations.models.YearsOfWorkField(decimal_places=1, max_digits=5, null=True)),
                ('talent_HR_remarks_json', models.TextField(blank=True, null=True)),
                ('talent_incident_record_json', models.TextField(blank=True, null=True)),
                ('talent_digital_file_storage_path_01', models.CharField(blank=True, max_length=2000, null=True)),
                ('talent_digital_file_storage_path_02', models.CharField(blank=True, max_length=2000, null=True)),
                ('talent_is_active', models.BooleanField(default=True)),
                ('talent_created_at', models.DateTimeField(auto_now_add=True)),
                ('talent_last_udpated_date', models.DateTimeField(auto_now=True)),
                ('talent_created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('talent_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='talent_management.talentsmodel')),
            ],
            options={
                'db_table': 'talent_managment',
                'ordering': ['-talent_id'],
            },
        ),
        migrations.CreateModel(
            name='TalentDocuments',
            fields=[
                ('document_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('talent_employment_docs', models.FileField(upload_to='2023_talent_employment_docs')),
                ('talent_uploaded_photos', models.ImageField(upload_to='photos')),
                ('uploaded_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('document_is_active', models.BooleanField(default=True)),
                ('talent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='talent_management.talentsmodel')),
            ],
            options={
                'db_table': 'talent_documents',
                'ordering': ['-talent_id'],
            },
        ),
    ]
