# Generated by Django 4.1.5 on 2023-05-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentsmodel',
            name='talent_hire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
