# Generated by Django 4.1.5 on 2023-05-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0002_alter_talentsmodel_talent_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentsmodel',
            name='talent_mailing_address_01',
            field=models.CharField(max_length=100, verbose_name='your street address 01'),
        ),
        migrations.AlterField(
            model_name='talentsmodel',
            name='talent_mailing_address_02',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' address 02 (apt numbers, unit #, etc)'),
        ),
        migrations.AlterField(
            model_name='talentsmodel',
            name='talent_pay_frequency',
            field=models.PositiveSmallIntegerField(choices=[(0, 'pay frequency not defined'), (1, 'daily'), (2, 'weekly'), (3, 'bi-weekly'), (4, 'semi-monthly'), (5, 'monthly'), (6, 'monthly'), (7, 'monthly'), (8, 'reserved pay frequency 1; not used yet'), (9, 'reserved pay frequency 1; not used yet')], default=0),
        ),
        migrations.AlterField(
            model_name='talentsmodel',
            name='talent_pay_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'unassigned pay type. Must be assigned before the first work day.'), (1, 'hourly'), (2, 'salaried'), (4, 'internship'), (3, 'bonus pay'), (5, 'pay type other-1'), (6, 'pay type other-2')], default=0),
        ),
    ]
