# Generated by Django 4.1.5 on 2023-05-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0003_alter_talentsmodel_talent_mailing_address_01_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentsmodel',
            name='talent_mailing_address_01',
            field=models.CharField(max_length=100, verbose_name='mailing address 01'),
        ),
        migrations.AlterField(
            model_name='talentsmodel',
            name='talent_mailing_address_02',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' mailing address 02 (apt numbers, unit #, etc)'),
        ),
        migrations.AlterField(
            model_name='talentsmodel',
            name='talent_physical_address_01',
            field=models.CharField(max_length=100, verbose_name='street address 01'),
        ),
        migrations.AlterField(
            model_name='talentsmodel',
            name='talent_physical_address_02',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='street address 02(apt numbers, unit #, etc.)'),
        ),
    ]
