# Generated by Django 4.1.5 on 2023-05-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0004_alter_talentsmodel_talent_mailing_address_01_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentsmodel',
            name='talent_certifications',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='talentsmodel',
            name='talent_mailing_address_city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='talentsmodel',
            name='talent_mailing_address_state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='talentsmodel',
            name='talent_pay_frequency',
            field=models.PositiveSmallIntegerField(choices=[(0, 'pay frequency not defined'), (1, 'daily'), (2, 'weekly'), (3, 'bi-weekly'), (4, 'semi-monthly'), (5, 'monthly'), (6, 'monthly'), (7, 'monthly'), (8, 'reserved pay frequency 1; not used yet'), (9, 'reserved pay frequency 2; not used yet')], default=0),
        ),
    ]
