# Generated by Django 4.1.5 on 2023-05-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0005_alter_talentsmodel_talent_certifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentsmodel',
            name='talent_HR_remarks_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talentsmodel',
            name='talent_incident_record_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talentsmodel',
            name='talent_mailing_address_is_the_same_physical_address',
            field=models.BooleanField(default=True),
        ),
    ]
