# Generated by Django 4.1.5 on 2023-06-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0006_alter_talentsmodel_talent_hr_remarks_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentsmodel',
            name='talent_work_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
