# Generated by Django 4.1.5 on 2023-06-02 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0007_talentsmodel_talent_work_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentsmodel',
            name='talent_digital_file_storage_path_01',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='talentsmodel',
            name='talent_digital_file_storage_path_02',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.CreateModel(
            name='TalentDocuments',
            fields=[
                ('document_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('talent_employment_docs', models.FileField(upload_to='2023_talent_employment_docs')),
                ('talent_uploaded_photos', models.ImageField(upload_to='photos')),
                ('talent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='talent_management.talentsmodel')),
            ],
        ),
    ]
