# Generated by Django 4.1.5 on 2023-06-02 23:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0008_talentsmodel_talent_digital_file_storage_path_01_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talentdocuments',
            options={'ordering': ['-talent_id']},
        ),
        migrations.AddField(
            model_name='talentdocuments',
            name='uploaded_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelTable(
            name='talentdocuments',
            table='talent_documents',
        ),
    ]
