# Generated by Django 4.1.5 on 2023-06-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0009_alter_talentdocuments_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentdocuments',
            name='document_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
