# Generated by Django 4.1.5 on 2023-06-16 00:36

import core_operations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0010_talentdocuments_document_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentsmodel',
            name='talent_phone_number_alternates_01',
            field=core_operations.models.FormattedPhoneNumberField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='talentsmodel',
            name='talent_phone_number_alternates_02',
            field=core_operations.models.FormattedPhoneNumberField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='talentsmodel',
            name='talent_phone_number_primary_digits_only',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='talentsmodel',
            name='talent_date_of_birth',
            field=models.DateField(null=True, verbose_name='your date of birth'),
        ),
    ]
