# Generated by Django 4.1.5 on 2023-06-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0011_talentsmodel_talent_phone_number_alternates_01_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentsmodel',
            name='talent_education_level',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='talentsmodel',
            name='talent_emergency_contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
