from .get_main_dash import get_main_dash

from .get_wip_dash_detail_v1 import get_wip_dash_detail_v1 
from .get_wip_dash_detail_v2 import get_wip_dash_detail_v2
from .dashboard_detail import DashboardDetailView
from .wip_dashboard import WIPDashboardView
from .get_repair_order_dash import get_repair_order_dash
from .repair_order_listview import RepairOrderListView
from .repair_order_update import RepairOrderUpdateView  # obselete
from .repair_order_udpate_method import repair_order_update  # obselete

from .line_item_three_in_one_update import line_item_three_in_one_update
from .line_item_three_in_one_create import line_item_three_in_one_create
from .line_item_merge_view import line_item_merge_view
from .line_item_update import LineItemUpdateView
from .labor_item_update import LaborItemUpdateView
from .repair_order_and_line_items_detail import repair_order_and_line_items_detail
from .repair_order_line_item_list import RepairOrderLineItemListView

from .chat_sidebar_view import chat_sidebar_view
from .search import SearchView

from .get_customer_dash import get_customer_dash
from .customer_create import CustomerCreateView
from .customer_detail import CustomerDetailView
from .customer_detail_v2 import CustomerDetail2View
from .update_customer_email import update_customer_email
from .customer_update import CustomerUpdateView
from .customer_delete import CustomerDeleteView

from .get_vehicle_dash import get_vehicle_dash
from .vehicle_detail import VehicleDetailView
from .vehicle_create import VehicleCreateView
from .vehicle_update import VehicleUpdateView
from .vehicle_delete import VehicleDeleteView

from .search_customer_by_phone import search_customer_by_phone
from .update_customer_assignment import update_customer_assignment
from .technican_dash import technician_dash_view

from .search_single_vin_via_nthsa_async import  search_single_vin_via_nhtsa
from .search_single_plate_via_palte2vin_async import search_single_plate_via_plate2vin
from .fetch_or_update_latest_vin_snapshot_async import fetch_or_save_latest_vin_snapshot_async